"""Add statistics models

Revision ID: 2b60da2617e4
Revises: 707d5c97ae88
Create Date: 2026-07-18 09:34:32.919011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b60da2617e4'
down_revision: Union[str, Sequence[str], None] = '707d5c97ae88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_logs_id'), 'chatbot_logs', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_logs_intent'), 'chatbot_logs', ['intent'], unique=False)
    op.create_index(op.f('ix_chatbot_logs_timestamp'), 'chatbot_logs', ['timestamp'], unique=False)
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_views_id'), 'product_views', ['id'], unique=False)
    op.create_index(op.f('ix_product_views_timestamp'), 'product_views', ['timestamp'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_timestamp'), 'sales', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_timestamp'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_product_views_timestamp'), table_name='product_views')
    op.drop_index(op.f('ix_product_views_id'), table_name='product_views')
    op.drop_table('product_views')
    op.drop_index(op.f('ix_chatbot_logs_timestamp'), table_name='chatbot_logs')
    op.drop_index(op.f('ix_chatbot_logs_intent'), table_name='chatbot_logs')
    op.drop_index(op.f('ix_chatbot_logs_id'), table_name='chatbot_logs')
    op.drop_table('chatbot_logs')
    # ### end Alembic commands ###
