"""Add model field to Product

Revision ID: 707d5c97ae88
Revises: d8ab1eace67f
Create Date: 2026-07-02 18:56:40.179905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707d5c97ae88'
down_revision: Union[str, Sequence[str], None] = 'd8ab1eace67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'model')
    # ### end Alembic commands ###
